INSERT INTO content_of_pages (title, mini_content, description, image_link, type) values ('Сергей Корсаков', 'Яндекс, Москва, менеджер проектов в отделе контент-системы', '"Матфак научил меня быть антишестерёнкой и уметь браться за любые задачи и проекты"', '/img/reviwes-page-photo/SergKorsakov.jpg', 'Graduates');
INSERT INTO content_of_pages (title, mini_content, description, image_link, type) values ('Ольга Кукина', 'Cеллинговое агентство при ВГТРК, Москва, бизнес-аналитик', '"Нас учили разбираться в том, что ты делаешь, а не просто зубрить и заучивать"', '/img/reviwes-page-photo/OlyaKukina.jpg', 'Graduates');
INSERT INTO content_of_pages (title, mini_content, description, image_link, type) values ('Николай Косарев', 'Quintiq, Голландия, разработчик и аналитик', '"Математика идеальна для обучения критическому мышлению и анализу"', '/img/reviwes-page-photo/NickKorsakov.jpg', 'Graduates');
INSERT INTO content_of_pages (title, mini_content, description, image_link, type) values ('Ольга Кукина', 'Cеллинговое агентство при ВГТРК, Москва, бизнес-аналитик', '"Нас учили разбираться в том, что ты делаешь, а не просто зубрить и заучивать"', '/img/reviwes-page-photo/OlyaKukina.jpg', 'Graduates');
INSERT INTO content_of_pages (title, mini_content, description, image_link, type) values ('Сергей Корсаков', 'Яндекс, Москва, менеджер проектов в отделе контент-системы', '"Матфак научил меня быть антишестерёнкой и уметь браться за любые задачи и проекты"', '/img/reviwes-page-photo/SergKorsakov.jpg', 'Graduates');
INSERT INTO content_of_pages (title, mini_content, description, image_link, type) values ('Николай Косарев', 'Quintiq, Голландия, разработчик и аналитик', '"Математика идеальна для обучения критическому мышлению и анализу"', '/img/reviwes-page-photo/NickKorsakov.jpg', 'Graduates');
INSERT INTO content_of_pages (title, mini_content, description, image_link, type) values ('Сергей Корсаков', 'Яндекс, Москва, менеджер проектов в отделе контент-системы', '"Матфак научил меня быть антишестерёнкой и уметь браться за любые задачи и проекты"', '/img/reviwes-page-photo/SergKorsakov.jpg', 'Graduates');
INSERT INTO content_of_pages (title, mini_content, description, image_link, type) values ('Ольга Кукина', 'Cеллинговое агентство при ВГТРК, Москва, бизнес-аналитик', '"Нас учили разбираться в том, что ты делаешь, а не просто зубрить и заучивать"', '/img/reviwes-page-photo/OlyaKukina.jpg', 'Graduates');
INSERT INTO content_of_pages (title, mini_content, description, image_link, type) values ('Николай Косарев', 'Quintiq, Голландия, разработчик и аналитик', '"Математика идеальна для обучения критическому мышлению и анализу"', '/img/reviwes-page-photo/NickKorsakov.jpg', 'Graduates');


